
#include <Qt>

#define EDITOR_PAN_KEY     Qt::Key_Space
#define EDITOR_SNAP_KEY    Qt::Key_Shift
#define EDITOR_REVERSE_KEY Qt::Key_Alt
#define EDITOR_DELETE_KEY  Qt::Key_Delete

#define EDITOR_INSERT_DIST 0.05

#define POINT_RADIUS 10
#define POINT_DIAMETER (POINT_RADIUS * 2)
#define POINT_INNER_RADIUS 2
#define POINT_INNER_DIAMETER (POINT_INNER_RADIUS * 2)
#define POINT_HANDLE_SELECTED_COLOR QColor(80, 80, 80, 255)
#define POINT_HANDLE_HOVER_COLOR QColor(120, 120, 120, 255)
