
import clip


class Curve(object):



class Timeline_Clip(object):
    def __init__(self):
        pass

    def time_to_frame(self, time):
        """
            Converts a discrete time into normalized time,
            and returns the frame generated by the Clip object
        """
        pass

    def set_start(self, time):
        pass

    def set_stop(self, time):
        pass

    def set_clip(self, clip):
        """ reference to an instantiated clip """
        pass

    def set_zone(self, zone):
        pass



class Timeline(object):
    def __init__(self):
        pass

    def time_to_frame(self, time):
        """ converts a timestamp to a graphics frame """
        pass

    def add_clip(self, timeline_clip):
        pass

    def remove_clip(self, timeline_clip):
        pass

    def add_curve(self, curve):
        pass

    def add_curve(self, curve):
        pass
