load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "liblzr",
    hdrs = [
        "liblzr.hpp",
    ],
    deps=[
        "//liblzr/core",
        "//liblzr/ilda",
        "//liblzr/dac",
        "//liblzr/optimizer",
    ],
    visibility = ["//visibility:public"],
)