load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "lzr",
    hdrs = [
        "lzr.hpp",
    ],
    deps=[
        "//lzr/core",
        "//lzr/ilda",
        "//lzr/dac",
        "//lzr/optimizer",
    ],
    visibility = ["//visibility:public"],
)